import React, { useContext } from "react";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import Ionicons from "@expo/vector-icons/Ionicons";
import { useNavigation } from "@react-navigation/native";
import { AuthContext } from "../Context/AuthContext";
import { colors, gradients } from "../design/theme";
export default function HeaderBar({location}){const navigation=useNavigation();const {user}=useContext(AuthContext);return <LinearGradient colors={gradients.primary} start={{x:0,y:0}} end={{x:1,y:1}} style={styles.header}><View style={styles.row}><View style={styles.brand}><View style={styles.logo}><Ionicons name="restaurant" size={22} color={colors.primary}/></View><View><Text style={styles.title}>Jafz Go Karo</Text><Text style={styles.subtitle}>Fresh food, fast delivery</Text></View></View><TouchableOpacity onPress={()=>navigation.navigate("Profile")} style={styles.icon}><Ionicons name="person-outline" size={21} color="#fff"/></TouchableOpacity></View><View style={styles.greetingRow}><View><Text style={styles.greeting}>Hi, {user?.displayName||"Food Lover"} 👋</Text><TouchableOpacity style={styles.location} onPress={()=>navigation.navigate("Settings")}><Ionicons name="location-outline" size={14} color="#fff"/><Text style={styles.locationText} numberOfLines={1}>{location?.label||"Getting your location..."}</Text></TouchableOpacity></View></View></LinearGradient>}
const styles=StyleSheet.create({header:{paddingHorizontal:16,paddingTop:12,paddingBottom:18,borderBottomLeftRadius:24,borderBottomRightRadius:24},row:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},brand:{flexDirection:"row",alignItems:"center"},logo:{width:42,height:42,borderRadius:14,backgroundColor:"#fff",alignItems:"center",justifyContent:"center",marginRight:10},title:{color:"#fff",fontSize:19,fontWeight:"900"},subtitle:{color:"rgba(255,255,255,.85)",fontSize:11,marginTop:2},icon:{width:42,height:42,borderRadius:14,backgroundColor:"rgba(255,255,255,.18)",alignItems:"center",justifyContent:"center"},greetingRow:{marginTop:14},greeting:{color:"#fff",fontSize:14,fontWeight:"700"},location:{flexDirection:"row",alignItems:"center",marginTop:5,maxWidth:"88%"},locationText:{color:"rgba(255,255,255,.9)",fontSize:12,fontWeight:"600",marginLeft:3}});
